JPERF-274: Avoid SSH leakage in tests
Avoid test stdout like:
```
18:00:07.934 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Broken transport; encountered EOF
net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
	at net.schmizz.sshj.transport.Reader.run(Reader.java:57) [sshj-0.23.0.jar:?]
```