Reduce test flakiness on WSL
Fix errors, when running integration tests on Windows Subsystem for Linux:
```
java.lang.Exception: Error while executing lftp -c 'set net:timeout 15; set net:max-retries 10; pget -n 32 -c "https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.2.0.tar.gz" -o test/atlassian-jira-software-7.2.0.tar.gz'. Exit status code SshResult(exitStatus=1, output=, errorOutput=pget: /software/jira/downloads/atlassian-jira-software-7.2.0.tar.gz: Fatal error: max-retries exceeded)
```

I don't know why [Ubuntu on Docker on WSL] requires more retries than [Ubuntu on Docker on OSX].