JPERF-449: Fix GPG apt-get error
Fix errors like:
```
java.lang.Exception: Error while executing sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic
 stable". Exit status code SshResult(exitStatus=100, output=Get:1 http://mirrors.ubuntu.com/mirrors.txt Mirrorlist [279 B]
Hit:2 http://ftp.vectranet.pl/ubuntu bionic InRelease
Get:3 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]
Err:3 https://download.docker.com/linux/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Reading package lists...
, errorOutput=W: GPG error: https://download.docker.com/linux/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu bionic InRelease' is not signed.
)
```