JPERF-273: Reduce integration test parallelism
Perhaps it will consume less disk space in peaks.
Try to avoid error on GitHub Actions:
```
com.atlassian.performance.tools.infrastructure.api.distribution.PublicJiraServiceDeskDistributionIT > shouldDownloadJiraServiceDesk FAILED
    java.lang.Exception at PublicJiraServiceDeskDistributionIT.kt:17
        Caused by: net.schmizz.sshj.connection.ConnectionException at PublicJiraServiceDeskDistributionIT.kt:17
            Caused by: java.util.concurrent.TimeoutException at PublicJiraServiceDeskDistributionIT.kt:17
java.io.IOException: No space left on device
com.esotericsoftware.kryo.KryoException: java.io.IOException: No space left on device
	at com.esotericsoftware.kryo.io.Output.flush(Output.java:165)
```